hub:
  image: selenium/hub 
  container_name:dockerTest
  ports:
     - "4444:4444"

Firefox:
  image: selenium/node-firefox:3.5 
  environment: 
    - NODE_MAX_INSTANCES=2 
    - NODE_MAX_SESSION=2
  links: 
    - hub

Chrome:
  image: selenium/node-chrome:3.5
  environment:
    - NODE_MAX_INSTANCES=2
    - NODE_MAX_SESSION=2 

  links:
    - hub
    
Execution:
    command: git clone https://github.com/kavita07/dockerComposeTest.git
    command: mvn clean install
    
services:
  git:
    image: git_sample_app_docker_compose:1.0
    container_name: git_sample_app_docker_compose
    build: .
    command: git -C /build clone https://github.com/leebrandt/docker-compose-example.git
    volumes:
      - ./build:/build