version: "3"
services:
    hub:
        image: selenium/hub
        container_name: selenium-hub
        ports:
            - "4444:4444"
    Firefox:
        image: selenium/node-firefox:3.5
        environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
        depends_on:
            - hub               
    Chrome:
        image: selenium/node-chrome:3.5
        environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
        depends_on:
            - hub       
    
    redis:
        image: "redis:3.2.3"
        hostname: redis
    
    git:
        image: git_sample_app_docker_compose:1.0
        container_name: git_sample_app_docker_compose
        build: .
        command: build https://github.com/kavita07/dockerComposeTest.git
        command: --redis-host redis
        volumes:
            - ./build:/build
        links:
            - "redis:redis"
    maven:
        image: maven:3.5-jdk-8-alpine
        build: .
        command: cd dockerComposeTest
        command: clean install
        volumes:
            - ./build:/build